apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-events-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
      - apiextensions.k8s.io/v1beta1
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    resources:
      - customresourcedefinitions
  - apiGroups:
      - argoproj.io
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    resources:
      - applications    #OBS added. need to add argocd application via kubectl in argo event sensor 
      - workflows
      - workflows/finalizers
      - gateways
      - gateways/finalizers
      - sensors
      - sensors/finalizers
  - apiGroups:
      - ""
    resources:
      - applications     #OBS added. need to add argocd application via kubectl in argo event sensor 
      - pods
      - pods/portforward #OBS added. needed for helm cmds 
      - pods/exec
      - configmaps
      - secrets
      - services
      - events
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - "apps/v1"
      - "apps/v1beta2"
      - "apps/v1beta1"
    resources:
      - deployments
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete