---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "maven-local-repo"
  namespace: "easy2use"
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 10Gi
  storageClassName: erikube-rbd
