#
#   Copyright 2019 Ericsson AB.
#   For a full list of individual contributors, please see the commit history.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-backend-prod
  # You'll usually want to add your resources.
  namespace: NAMESPACE_TO_SED
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: http://GERRIT_INGRESS_TO_SED/deployments.git
    targetRevision: master
    path: ms-backend

    # helm specific config
    helm:
      valueFiles:
      - values-prod.yaml

    # directory
    #directory:
    #  recurse: true

    # plugin specific config
    #plugin:
    #- name: mypluginname

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: NAMESPACE_TO_SED

  # Sync policy
  syncPolicy:
    automated:
      prune: true

  # Ignore differences at the specified json pointers
  #ignoreDifferences:
  #- group: apps
  #  kind: Deployment
  #  jsonPointers:
  #  - /spec/replicas